Documents public API and types.
EventStore/EventStore-Client-Go pull request #120
Opened 2022-05-16 12:49 UTC by YoEight

2022-05-19 12:12 UTC, hayley-jean requested changes

2022-05-19 12:12 UTC, hayley-jean commented on esdb/types.go
> +// AddReadRoles Adds delete roles.
```suggestion
// AddReadRoles Adds read roles.
```

2022-05-19 12:12 UTC, hayley-jean commented on esdb/types.go
> +// soft-deletions of streams.
```suggestion
// deletions of streams.
```

2022-05-19 12:12 UTC, hayley-jean commented on esdb/types.go
> +// TruncateBefore The event number from which previous events can be scavenged. This is used to implement soft-deletions
```suggestion
// TruncateBefore The event number from which previous events can be scavenged. This is used to implement deletions
```

2022-05-19 12:12 UTC, hayley-jean commented on esdb/types.go
> +// ExcludeSystemEventsFilter filters out event's with system's event types.
Should this include the fact that system event types start with a `$`?
```suggestion
// ExcludeSystemEventsFilter filters out event's with system's event types, i.e. event types starting with `$`.
```

2022-05-19 12:12 UTC, hayley-jean commented on esdb/types.go
> +	// Number of events seen since last measurement on this connection.
```suggestion
	// Number of events seen since last measurement on this subscription.
```

2022-05-19 12:12 UTC, hayley-jean commented on esdb/types.go
> +	// Total number of events processed by subscriptions.
```suggestion
	// Total number of events processed by this subscription.
```

2022-05-24 10:11 UTC, YoEight commented on esdb/client.go
> +// subsequently written events.
Done.

2022-05-24 10:38 UTC, hayley-jean submitted a review, later dismissed

2022-05-24 12:19 UTC, pvanbuijtene approved these changes

2022-05-25 11:13 UTC, pvanbuijtene approved these changes

2022-05-25 11:35 UTC, hayley-jean approved these changes

2022-05-25 11:35 UTC, merged