Respect the discoveryInterval connection configuration option.
EventStore/EventStore-Client-Go pull request #121
Opened 2022-05-18 09:21 UTC by kristinn

The discoveryInterval connection configuration option exists on the
configuration object, but there is no logic that actually handles
discovery intervals.

This commit introduces the missing logic for handling discovery
intervals.

2022-05-19 10:19 UTC, hayley-jean submitted a review, later dismissed
Thanks for the PR @kristinn 
I've tested this locally and it looks good to me 👍

2022-05-19 10:20 UTC, kristinn commented
> Thanks for the PR @kristinn I've tested this locally and it looks good to me +1

My pleasure! Great to hear! :-)

Thanks for the quick response!

2022-05-19 11:01 UTC, YoEight requested changes
I think it would be better to add the `Sleep` statement after looping through candidates. That way, checking for `attempt > 0` is no longer needed.

2022-05-19 12:16 UTC, hayley-jean approved these changes

2022-05-20 10:54 UTC, YoEight approved these changes
Thanks for your PR!

2022-05-20 10:54 UTC, merged