feat: add OriginalStreamRevision to ResolvedEvent
EventStore/EventStore-Client-Go pull request #163
Opened 2024-01-16 03:32 UTC by yordis

Added: OriginalStreamRevision to ResolvedEvent

## Context

When developing a Optimistic Concurrency Check, I made a mistake, that having a function like this one would prevent to some extent:

```go
func getExpectedRevision(opts *Options, lastResolvedEvent *esdb.ResolvedEvent) ExpectedRevision {
	if opts != nil && opts.ExpectedRevision != nil {
		return opts.ExpectedRevision
	} else if lastResolvedEvent == nil {
		return NoStream{}
	} else {
                // I did this
                return Revision(lastResolvedEvent.Event.EventNumber)
	}
}
```

2024-01-17 01:25 UTC, YoEight requested changes
Hey @yordis and thanks for your first contribution!

I'm fine with this change but could you amend commit message to match the format we already have in place, please?

For example, it could be:

```
Add OriginalStreamRevision to ResolvedEvent
```

2024-01-17 01:46 UTC, yordis commented
Done

2024-01-19 04:10 UTC, YoEight approved these changes
Thanks for your contribution.

2024-01-19 04:11 UTC, merged

2024-01-27 04:46 UTC, yordis commented
@YoEight, do you think it is possible to make a release with the latest features?

2024-01-27 05:09 UTC, YoEight commented
Sure, give me a few minutes

2024-01-27 05:14 UTC, YoEight commented
@yordis Done, release v3.3.0 is available with your latest changes!