Re-expose persistent subscription connect function.
EventStore/EventStore-Client-Go pull request #83
Opened 2021-11-24 10:05 UTC by YoEight

Fixes #82

2021-11-25 08:35 UTC, ylorph commented
@YoEight : on windows all  tests pass  without issue for the matrix 20.10.4-buster-slim, 21.6.0-buster-slim, ci

2021-11-25 08:38 UTC, ylorph reviewed
ok for me , 
 ! we need to create an issue for the naming convention `connect` vs `subscribe`
 for both the persistent subcription to all & to a group/stream 
 
 that should'nt block the merge imho

2021-11-25 08:39 UTC, ylorph requested changes
We need a note in the readme for the EVENTSTORE_DOCKER_TAG_ENV if people want to run the test against a specific database version .

2021-11-25 12:19 UTC, George-Payne commented on esdb/client.go
> +func (client *Client) ConnectToPersistentSubscriptionToAll(
The RFC calls this method `SubscribeToPersistentSubscriptionToAll`

https://github.com/EventStore/architecture-and-planning/blob/main/rfcs/022%20-%20gRPC%20Persistent%20Subscriptions.md#supported-operations

2021-11-25 12:20 UTC, George-Payne commented on esdb/client.go
> +func (client *Client) ConnectToPersistentSubscriptionToAll(
Oh, just saw Yves's comment, ignore me.

2021-11-25 12:34 UTC, George-Payne commented on esdb/client.go
> +func (client *Client) ConnectToPersistentSubscriptionToAll(
Yeah, also needs to be changed in `ConnectToPersistentSubscription`, so good to do a single alignment PR.

2021-11-26 07:11 UTC, YoEight commented
@George-Payne @ylorph The issue was created there: https://github.com/EventStore/EventStore-Client-Go/issues/85

2021-11-26 12:28 UTC, ylorph approved these changes

2021-11-29 13:28 UTC, hayley-jean approved these changes
This looks good, the names can be aligned in a different PR since there's also things like `BatchSize` vs `BufferSize` to check as well.

2021-11-29 14:13 UTC, merged