Apply Persistent Subscriptions RFC - 022.
EventStore/EventStore-Client-Go pull request #87
Opened 2021-11-30 16:27 UTC by YoEight

2021-12-08 10:18 UTC, YoEight commented
@ylorph samples added!

2021-12-09 07:40 UTC, ylorph commented
I'm missing or missed in the sample
CreatePersistentSubscription
ConnectToPersistentSubscriptionToAll ( i.e no manual ACK)

( those are manily to have the correcect samples to point to from the docs )

2021-12-09 11:35 UTC, YoEight commented on esdb/persistent_options.go
>  	MaxSearchWindow    int
It's used to configure the filter.

2021-12-09 11:36 UTC, YoEight commented
@ylorph I added the missing create persistent subscription sample.

2021-12-09 12:17 UTC, ylorph commented on esdb/persistent_options.go
>  	MaxSearchWindow    int
I'm not seing  CheckpointInterval  as a specific setting for filter in the  .net client

2021-12-09 16:59 UTC, ylorph approved these changes

2021-12-13 16:21 UTC, pvanbuijtene requested changes

2021-12-13 16:21 UTC, pvanbuijtene commented on esdb/types.go
> +	TotalItemsProcessed      int64                         `json:"totalItemsPerSecond"`
Is `totalItemsPerSecond` different for a reason?

2021-12-16 10:37 UTC, pvanbuijtene approved these changes

2021-12-17 11:13 UTC, thefringeninja approved these changes

2021-12-17 11:13 UTC, merged